# Generated by Django 5.1.1 on 2024-09-04 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=250)),
                ('user_type', models.CharField(choices=[('client', 'Client'), ('professional', 'Professional')], max_length=250)),
                ('email', models.EmailField(max_length=250)),
            ],
        ),
    ]
