# Generated by Django 5.1.1 on 2024-09-04 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='user_type',
            field=models.CharField(choices=[('client', 'Client'), ('careprovider', 'Professional')], max_length=250),
        ),
    ]
