# Generated by Django 5.1.1 on 2024-09-05 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_usermodel_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
