# Generated by Django 5.1.1 on 2024-09-05 04:35

from django.db import migrations
from api.models import UserModel

class Migration(migrations.Migration):
    def create_user(apps, schema_editor):

        UserModel.objects.create(
            user_id = "123",
            user_type = UserModel.UserTypes.PROFESSIONAL,
            email = "test@gmail.com"
        )

    dependencies = [
        ('api', '0003_alter_usermodel_id'),
    ]

    operations = [
           migrations.RunPython(create_user),
    ]
